name: Add or update member profile 🧑‍🔬
description: |
  Fill this form to add or update a lab member's profile on the website.
title: "[Add/update member]"
labels: ["automatic-add-update-member"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        If you choose to *add* a member's profile, fill out as many fields as possible. If you choose to *update* a member's profile, *only* fill out the required fields and the fields that you want to modify. Leave everything else blank.
        
        When updating a profile, it will match the profile with the same full `name`. If multiple people have the same full name, it will match the first one encountered. In this case, you might want to to either make the change manually or move an older profile to the bottom (both require editing the YAML file).

        This form will automatically generate a PR that will be reviewed by the maintainers.

  - type: dropdown
    id: action
    attributes:
      label: Action
      description: What do you want to do?
      options:
        - "Add member"
        - "Update member"
    validations:
      required: true
  
  - type: input
    id: name
    attributes:
      label: Name
      description: Full name of the lab member
      placeholder: "John Doe"
    validations:
      required: true

  - type: dropdown
    id: role
    attributes:
      label: "Role"
      description: What's the role of the lab member?
      multiple: false
      options:
        - "Faculty"
        - "Adjunct Faculty"
        - "Postdoc"
        - "PhD"
        - "Master"
        - "Undergraduate"
        - "Intern"
        - "Research Engineer"
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: "Status"
      description: >
        What's the current status of the lab member?
      multiple: false
      options:
        - "Alumni"
        - "Current Member"
    validations:
      required: true

  - type: input
    id: username
    attributes:
      label: "Username"
      description: >
        Mila username, for example `jon.doe` if `jon.doe@mila.quebec` is your Mila email address.
        
    validations:
      required: true

  - type: input
    id: semantic_scholar_id
    attributes:
      label: "Semantic Scholar ID"
      description: |
        If you have a [Semantic Scholar](https://www.semanticscholar.org) ID, enter it here. This is highly recommend becasue it is used to automatically attribute a paper to the correct author.
      placeholder: "145113126"
    validations:
      required: false

  - type: textarea
    id: avatar
    attributes:
      label: "Avatar"
      description: |
        Path or URL or image of the avatar of the lab member. If it's a URL, it will be automatically resized and saved to `/assets/images/bio`.
        
        Tip: You can drag and drop an image, or click on the "M" button on the bottom right of the text area.   
        Otherwise, you can use imgur and give the **direct** link (for example `https://i.imgur.com/id.png`, `https://user.github.io/assets/headshot.jpg`, etc.).
        Do NOT use indirect links to webpages that contains an image, this will not be parsed correctly.
      
      placeholder: "Click here and drag an image to upload, or paste an image URL"
    validations:
      required: false

  - type: "input"
    id: advisor
    attributes:
      label: "Advisor"
      description: "For students, who is/are the advisor(s) from the faculty members of McGill NLP? Separate multiple names with a comma."
      placeholder: "John Doe Sr., Jane Doe"
    validations:
      required: false

  - type: "input"
    id: date
    attributes:
      label: "Date"
      description: "When did the lab member join the lab? MMM-YYYY or {Fall, Summer, Winter} YYYY"
      placeholder: "Jan 2021"
    validations:
      required: false

  - type: "input"
    id: bio
    attributes:
      label: "Bio"
      description: "A description of the lab member in one sentence (or less than 10 words)."
      placeholder: "Works on Artificial Generic Intelligence"

  - type: "input"
    id: note
    attributes:
      label: "Note"
      description: "Any special note you want to include in one sentence. For example, fellowship, co-advisor, etc."
      placeholder: "Co-advised by Alan Turing"

  - type: "input"
    id: github
    attributes:
      label: "GitHub"
      description: "Full URL of the lab member's GitHub profile"
      placeholder: "https://github.com/john-doe"
    validations:
      required: false
  
  - type: "input"
    id: twitter
    attributes:
      label: "Twitter"
      description: "Full URL of the lab member's Twitter profile"
      placeholder: "https://twitter.com/john-doe"
    validations:
      required: false
    
  - type: "input"
    id: scholar
    attributes:
      label: "Scholar"
      description: "Full URL of the lab member's Google Scholar profile"
      placeholder: "https://scholar.google.com/citations?user=<user_id>"
    validations:
      required: false

  - type: "input"
    id: website
    attributes:
      label: "Website"
      description: "Full URL of the lab member's website"
      placeholder: "https://john-doe.github.io/"
    validations:
      required: false

  - type: "input"
    id: new_role
    attributes:
      label: "New Role"
      description: "Only if the lab member is an alumni, what's the new role?"
      placeholder: "Professing at Leland S. Junior University"
    validations:
      required: false
